import collar from "../../assets/products/collar.jpg";

import petFood from "../../assets/products/food3.jpg";
import pets from "../../assets/products/food4.jpg";
import ropa from "../../assets/products/ropa3.jpg";
import ropa1 from "../../assets/products/ropa1.jpg";
import medicine from "../../assets/products/medicina.jpg";
import petToy from "../../assets/products/juguete2.jpg";

import cepillo from "../../assets/products/cepillo.jpg";

import shampoo from "../../assets/products/shampoo-para-mascotas.jpg";


import combo from "../../assets/products/combo.jpg"
import contornoDeOjos from "../../assets/products/contornoDeOjos.jpg"
import hidratante from "../../assets/products/hidratante.jpg"
import hidratante1 from "../../assets/products/hidratante1.jpg"
import serum from "../../assets/products/serum.jpg"
import sunProtect from "../../assets/products/sunProtect.jpg"
import  sunProtects from "../../assets/products/sunProtects.jpg"





export const MOCK_DATA = [
  {
    id: 1,
    nombre: "Collar",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "combos",
    img: combo,
    stock:5,
    sizes : [
      {
        value: "S",
        label: "Small"
      },
      {
        value: "M",
        label: "Medium"
      },
      {
        value: "L",
        label: "Largue"
      }
     ],
  },
  {
    id: 2,
    nombre: "Corta uñas",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "Contorno de ojos",
    img: contornoDeOjos,
    stock:5,
    sizes:  [
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 3,
    nombre: "Hueso de goma",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "Crema hidratante",
    img: hidratante,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 4,
    nombre: "Bolsa",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "Crema hidratante",
    img: hidratante1,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },

  {
    id: 5,
    nombre: "Alimento para perros",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "serum",
    img:serum,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 6,
    nombre: "Peluche de elefante",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "Protector solar",
    img: sunProtect,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 7,
    nombre: "Snack",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "alimento",
    img: sunProtects,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 8,
    nombre: "Alimento",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "alimento",
    img: petFood,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 9,
    nombre: "Snack tranquilizante",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "alimento",
    img: pets,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 10,
    nombre: "Cuernos de reno",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "accesorios",
    img: ropa,
    stock:5,
    sizes : [
      {
        value: "S",
        label: "Small"
      },
      {
        value: "M",
        label: "Medium"
      },
      {
        value: "L",
        label: "Largue"
      }
     ],
  },
  {
    id: 11,
    nombre: "Shampoo en barra",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "higiene",
    img: shampoo,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 12,
    nombre: "Atención medica",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "medicina",
    img: medicine,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 13,
    nombre: "Juguete para gato",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "juguetes",
    img: petToy,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 14,
    nombre: "Cepillo",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "higiene",
    img: cepillo,
    stock:5,
    sizes:[
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      },
      {
        value: null,
        label: null
      }
     ],
  },
  {
    id: 15,
    nombre: "Ropa navideña",
    descripcion: "Lorem ipsum dolor sit amet, consectetur ",
    precio: 1500,
    category: "accesorios",
    img: ropa1,
    stock:5,
    sizes : [
      {
        value: "S",
        label: "Small"
      },
      {
        value: "M",
        label: "Medium"
      },
      {
        value: "L",
        label: "Largue"
      }
     ],
  },
];
